# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/worksphere
spring.datasource.username=postgres
spring.datasource.password=120012
# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=true
spring.profiles.active=dev
server.error.include-message=always
#JWT-SECRET_KEY
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

# Mailtrap Settings
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=020321b68b1a29
spring.mail.password=aea83585c86ecc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.transport.protocol=smtp